services:
  db:
    image: pgvector/pgvector:pg16
    container_name: semantic_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: semantic_search
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=1GB
      -c work_mem=128MB
      -c maintenance_work_mem=512MB
      -c max_wal_size=2GB
volumes:
  pgdata:
